[package]
name = "cmyudi"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
viuer = { version = "0.10.0", features = ["print-file"] }
crossterm = "0.29.0"
term_size = "0.3"
rand = "0.9.2"
ctrlc = "3.5.1"
